// Top 200 Sites Scraper — extracts design data + screenshots for each site
// Usage: npx tsx scripts/scrape-top-sites.ts
import { fileURLToPath } from 'url';
import { dirname, join } from 'path';
import * as fs from 'fs';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const OUTPUT_DIR = join(__dirname, '..', 'public', 'top-sites');
const SCREENSHOTS_DIR = join(OUTPUT_DIR, 'screenshots');
const DATA_FILE = join(OUTPUT_DIR, 'sites.json');

// Ensure dirs exist
fs.mkdirSync(SCREENSHOTS_DIR, { recursive: true });

// Screenshot URLs — using free screenshot services
function getScreenshotUrl(url: string, width = 1280, height = 800): string {
  // WordPress mShots — free, no auth, reliable
  return `https://s.wordpress.com/mshots/v1/${encodeURIComponent(url)}?w=${width}&h=${height}`;
}

// Extract design data from HTML
function extractDesignData(html: string, url: string, name: string): any {
  // Extract colors from inline styles and CSS
  const colors = new Set<string>();
  const colorRegex = /(?:color|background-color|background|border-color|fill|stroke):\s*(#[0-9a-fA-F]{3,8}|rgb\([^)]+\)|rgba\([^)]+\))/g;
  let match;
  while ((match = colorRegex.exec(html)) !== null) {
    const color = match[1];
    if (color.startsWith('#')) {
      colors.add(color.toUpperCase());
    }
  }

  // Extract font families
  const fonts = new Set<string>();
  const fontRegex = /font-family:\s*([^;}"']+)/g;
  while ((match = fontRegex.exec(html)) !== null) {
    const font = match[1].trim().split(',')[0].replace(/['"]/g, '').trim();
    if (font && !['inherit', 'initial', 'sans-serif', 'serif', 'monospace', 'system-ui', '-apple-system', 'BlinkMacSystemFont'].includes(font)) {
      fonts.add(font);
    }
  }

  // Extract meta theme-color
  const themeColorMatch = html.match(/<meta[^>]+name=["']theme-color["'][^>]+content=["']([^"']+)["']/i);
  const themeColor = themeColorMatch ? themeColorMatch[1] : '';

  // Extract title
  const titleMatch = html.match(/<title>([^<]+)<\/title>/i);
  const title = titleMatch ? titleMatch[1].trim() : name;

  // Extract description
  const descMatch = html.match(/<meta[^>]+name=["']description["'][^>]+content=["']([^"']+)["']/i);
  const description = descMatch ? descMatch[1].trim() : '';

  // Classify palette
  const colorArray = Array.from(colors).slice(0, 10);
  const isDark = colorArray.some(c => {
    const hex = c.replace('#', '');
    const r = parseInt(hex.substr(0, 2), 16);
    const g = parseInt(hex.substr(2, 2), 16);
    const b = parseInt(hex.substr(4, 2), 16);
    return (r + g + b) / 3 < 60;
  });

  return {
    url,
    name,
    title,
    description,
    themeColor,
    colors: colorArray,
    fonts: Array.from(fonts).slice(0, 5),
    isDark,
    scrapedAt: new Date().toISOString(),
  };
}

// Generate DESIGN.md from extracted data
function generateSiteDesignMd(site: any, data: any): string {
  const colorsSection = data.colors.length > 0
    ? data.colors.map((c: string, i: number) => `### Color ${i + 1}\n\`${c}\``).join('\n\n')
    : '### Theme Color\n`' + (data.themeColor || '#000000') + '`';

  const fontsSection = data.fonts.length > 0
    ? data.fonts.map((f: string) => `- ${f}`).join('\n')
    : '- system-ui (no custom fonts detected)';

  return `# ${site.name}

> ${site.description}

**URL:** ${site.url}
**Category:** ${site.category}
**Theme:** ${data.isDark ? 'Dark' : 'Light'}

## Extracted Colors

${colorsSection}

## Extracted Fonts

${fontsSection}

## Page Title

${data.title}

## Meta Description

${data.description || 'N/A'}

## Design Notes

- **Color palette:** ${data.colors.length} unique colors detected from inline styles
- **Typography:** ${data.fonts.length} custom font families detected
- **Theme:** ${data.isDark ? 'Dark mode (dark backgrounds detected)' : 'Light mode (light backgrounds)'}
- **Theme color:** ${data.themeColor || 'Not specified'}

## Source

Extracted from ${site.url} on ${data.scrapedAt}

---
*Generated by OpenDesignStudio Top 200 Scraper*
`;
}

async function main() {
  // Import the top sites list
  const { topSites } = await import(join(__dirname, '..', 'src', 'data', 'topSites.ts'));

  const results: any[] = [];

  console.log(`Scraping ${topSites.length} top sites...`);

  for (let i = 0; i < topSites.length; i++) {
    const site = topSites[i];
    console.log(`[${i + 1}/${topSites.length}] ${site.name} (${site.url})`);

    try {
      // Fetch the page HTML
      const response = await fetch(site.url, {
        headers: { 'User-Agent': 'Mozilla/5.0 (compatible; OpenDesignStudio/1.0)' },
        signal: AbortSignal.timeout(10000),
      });
      const html = await response.text();

      // Extract design data
      const data = extractDesignData(html, site.url, site.name);

      // Generate DESIGN.md
      const designMd = generateSiteDesignMd(site, data);

      // Save DESIGN.md
      const mdPath = join(OUTPUT_DIR, `${site.name.toLowerCase().replace(/[^a-z0-9]/g, '-')}.md`);
      fs.writeFileSync(mdPath, designMd);

      // Screenshot URL (we'll store the URL, not download — saves bandwidth)
      const screenshotUrl = getScreenshotUrl(site.url);

      results.push({
        ...site,
        ...data,
        screenshotUrl,
        designMdPath: `${site.name.toLowerCase().replace(/[^a-z0-9]/g, '-')}.md`,
      });

      console.log(`  ✅ ${data.colors.length} colors, ${data.fonts.length} fonts, ${data.isDark ? 'dark' : 'light'}`);
    } catch (e: any) {
      console.log(`  ❌ ${e.message}`);
      // Still add with minimal data
      const screenshotUrl = getScreenshotUrl(site.url);
      results.push({
        ...site,
        colors: [],
        fonts: [],
        themeColor: '',
        isDark: false,
        title: site.name,
        description: site.description,
        screenshotUrl,
        designMdPath: `${site.name.toLowerCase().replace(/[^a-z0-9]/g, '-')}.md`,
        error: e.message,
        scrapedAt: new Date().toISOString(),
      });

      // Write minimal DESIGN.md
      const designMd = generateSiteDesignMd(site, { colors: [], fonts: [], themeColor: '', isDark: false, title: site.name, description: site.description, scrapedAt: new Date().toISOString() });
      fs.writeFileSync(join(OUTPUT_DIR, `${site.name.toLowerCase().replace(/[^a-z0-9]/g, '-')}.md`), designMd);
    }

    // Rate limit
    if (i < topSites.length - 1) {
      await new Promise(r => setTimeout(r, 300));
    }
  }

  // Write sites.json
  fs.writeFileSync(DATA_FILE, JSON.stringify(results, null, 2));
  console.log(`\nDone! ${results.length} sites scraped`);
  console.log(`Data: ${DATA_FILE}`);
  console.log(`Screenshots: ${SCREENSHOTS_DIR} (using WordPress mShots URLs)`);
  console.log(`DESIGN.md files: ${OUTPUT_DIR}`);
}

main().catch(console.error);
